run:
  timeout: 5m
  go: "1.22"

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - revive
    - gocritic
    - gosec
    - misspell
    - unconvert
    - prealloc
    - nilerr
    - errorlint

linters-settings:
  govet:
    enable-all: true
    disable:
      - fieldalignment

  revive:
    rules:
      - name: var-naming
      - name: package-comments
      - name: exported
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: indent-error-flow
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: unreachable-code

  gocritic:
    enabled-tags:
      - diagnostic
      - performance
      - style

  errcheck:
    check-type-assertions: true
    check-blank: false

issues:
  exclude-dirs:
    - web
    - bin
    - migrations
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
