// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/ports.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/ports.go -destination=internal/persistence/mocks/mock_repos.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/joajo13/go-tracker/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockTickerRepo is a mock of TickerRepo interface.
type MockTickerRepo struct {
	ctrl     *gomock.Controller
	recorder *MockTickerRepoMockRecorder
	isgomock struct{}
}

// MockTickerRepoMockRecorder is the mock recorder for MockTickerRepo.
type MockTickerRepoMockRecorder struct {
	mock *MockTickerRepo
}

// NewMockTickerRepo creates a new mock instance.
func NewMockTickerRepo(ctrl *gomock.Controller) *MockTickerRepo {
	mock := &MockTickerRepo{ctrl: ctrl}
	mock.recorder = &MockTickerRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTickerRepo) EXPECT() *MockTickerRepoMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockTickerRepo) Get(ctx context.Context, id domain.TickerID) (domain.Ticker, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(domain.Ticker)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockTickerRepoMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockTickerRepo)(nil).Get), ctx, id)
}

// Insert mocks base method.
func (m *MockTickerRepo) Insert(ctx context.Context, t *domain.Ticker) (domain.TickerID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, t)
	ret0, _ := ret[0].(domain.TickerID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Insert indicates an expected call of Insert.
func (mr *MockTickerRepoMockRecorder) Insert(ctx, t any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockTickerRepo)(nil).Insert), ctx, t)
}

// ListActive mocks base method.
func (m *MockTickerRepo) ListActive(ctx context.Context) ([]domain.Ticker, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListActive", ctx)
	ret0, _ := ret[0].([]domain.Ticker)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListActive indicates an expected call of ListActive.
func (mr *MockTickerRepoMockRecorder) ListActive(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListActive", reflect.TypeOf((*MockTickerRepo)(nil).ListActive), ctx)
}

// MockPriceRepo is a mock of PriceRepo interface.
type MockPriceRepo struct {
	ctrl     *gomock.Controller
	recorder *MockPriceRepoMockRecorder
	isgomock struct{}
}

// MockPriceRepoMockRecorder is the mock recorder for MockPriceRepo.
type MockPriceRepoMockRecorder struct {
	mock *MockPriceRepo
}

// NewMockPriceRepo creates a new mock instance.
func NewMockPriceRepo(ctrl *gomock.Controller) *MockPriceRepo {
	mock := &MockPriceRepo{ctrl: ctrl}
	mock.recorder = &MockPriceRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPriceRepo) EXPECT() *MockPriceRepoMockRecorder {
	return m.recorder
}

// Insert mocks base method.
func (m *MockPriceRepo) Insert(ctx context.Context, p *domain.Price) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, p)
	ret0, _ := ret[0].(error)
	return ret0
}

// Insert indicates an expected call of Insert.
func (mr *MockPriceRepoMockRecorder) Insert(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockPriceRepo)(nil).Insert), ctx, p)
}

// LatestByTicker mocks base method.
func (m *MockPriceRepo) LatestByTicker(ctx context.Context, id domain.TickerID) (domain.Price, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LatestByTicker", ctx, id)
	ret0, _ := ret[0].(domain.Price)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LatestByTicker indicates an expected call of LatestByTicker.
func (mr *MockPriceRepoMockRecorder) LatestByTicker(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LatestByTicker", reflect.TypeOf((*MockPriceRepo)(nil).LatestByTicker), ctx, id)
}
